# TETR

spacing         = 2
padding         = 0
hide_ascii      = false
separator       = "<->"
key_color       = "#F50093"
separator_color = "#F61067"

[palette]
type = "Full"
visible = true

[box]
border          = "double"
visible         = false

[box.inner_margin]
x               = 0
y               = 0

[randomize]
key_color       = false
separator_color = false

[keys]
host            = "TETR"
kernel          = "Kernel"
battery         = "Battery"
os              = "OS"
de              = "DE"
wm              = "WM"
distro          = "Distro"
terminal        = "Terminal"
shell           = "Shell"
packages        = "Packages"
uptime          = "Uptime"
memory          = "Memory"
local_ip        = "Local IP"
backlight       = "Brightness"
resolution      = "Resolution"
cpu_load        = "CPU Load"
cpu             = "CPU"
gpu             = "GPU"
disk_space      = "Disk Space"

[custom_ascii]
color = "#ff0cd2"
path = "/home/tetr/.config/macchina/ascii/penta_medium.ascii"
