#!/bin/sh
#/ This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 100	# Set DPI. User may want to use a larger number for larger screens.
xset s off # screen blanking off
xset -dpms # disable dpms

autostart="remapd dunst unclutter pipewire mpd ex-macchina"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1
